name: json_schema_to_freezed
description: Convert JSON schema files to Dart classes with Freezed or regular Dart classes with JSON serialization support.
version: 1.0.0
repository: https://github.com/joaopedrosouza/json_schema_to_freezed
homepage: https://github.com/joaopedrosouza/json_schema_to_freezed
documentation: https://github.com/joaopedrosouza/json_schema_to_freezed/blob/main/README.md
issue_tracker: https://github.com/joaopedrosouza/json_schema_to_freezed/issues

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.3.0
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
